version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: gomod
    directory: /http
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: gomod
    directory: /chi
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: gomod
    directory: /echo
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: gomod
    directory: /fiber
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: gomod
    directory: /gin
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: gomod
    directory: /huma
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: gomod
    directory: /benchmarks
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: gomod
    directory: /integrationtests
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: weekly
    groups:
      documentation:
        patterns: ["*"]
    commit-message:
      prefix: chore
      include: scope
