version: "2"
run:
  go: 1.25.0
linters:
  enable:
    - copyloopvar
    - gocritic
    - gocyclo
  disable:
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - nestif
  settings:
    funlen:
      lines: 100
      statements: 50
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 30
    gomodguard:
      blocked:
        modules:
          - github.com/pkg/errors:
              recommendations:
                - errors
                - fmt
              reason: use standard library errors package
    govet:
      enable:
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - funlen
          - gochecknoglobals
          - goconst
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - unused
        path: vendor/
      - linters:
          - unused
        text: is unused
        source: ^\s*\w+\s+interface\s*{
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
