name: PR Check

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  statuses: write

jobs:
  conventional-commits:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure allowed types
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Configure allowed scopes (optional)
          scopes: |
            provider
            collection
            module
            lifetime
            descriptor
            errors
            inout
            scope
            resolver
            deps
          # Require scope to be provided
          requireScope: false
          # Subject requirements
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.

  check-commits:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
          helpURL: https://github.com/junioryono/godi/blob/main/CONTRIBUTING.md#commit-message-convention
