name: PR Labeler

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label PR based on type
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on title
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          script: |
            const title = context.payload.pull_request.title.toLowerCase();
            const labels = [];

            // Determine type based on conventional commit format
            if (title.startsWith('feat')) {
              labels.push('type: feature');
            } else if (title.startsWith('fix')) {
              labels.push('type: bug');
            } else if (title.startsWith('docs')) {
              labels.push('type: documentation');
            } else if (title.match(/^(build|chore|ci|perf|refactor|revert|style|test)/)) {
              labels.push('type: maintenance');
            }

            // Check for breaking changes
            if (title.includes('!:') || title.includes('breaking')) {
              labels.push('type: breaking');
            }

            // Add labels if any were determined
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labels
              });
            }
